name: Build Pull Request
on: pull_request

jobs:
  build:
    name: Build pull request
    runs-on: ubuntu-latest
    env:
      JAVA_OPTS: -Xmx2g -Dorg.gradle.daemon=false
    #services:
    #  flow-emulator:
    #    image: gcr.io/flow-container-registry/emulator
    #    env:
    #      FLOW_VERBOSE: true
    #      FLOW_PORT: 3569
    #      FLOW_INTERVAL: 5s
    #      FLOW_PERSIST: false
    #    ports:
    #      - 3569:3569
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          java-package: jdk
          distribution: 'adopt'

      - name: Install flow emulator
        run: sh -ci "$(curl -fsSL https://storage.googleapis.com/flow-cli/install.sh)"

      - name: Make gradle executable
        run: chmod +x ./gradlew

      - name: Build
        id: build
        run: ./gradlew --warning-mode all check build -x test -x integrationTest

      - name: Run Unit Tests
        id: unit_test
        if: ${{ steps.build.outcome == 'success' }}
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          ./gradlew --no-daemon --max-workers=2 --warning-mode=all test --continue --stacktrace

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.18
        if: always()
        with:
          check_name: "Unit Test Results"
          files: "**/test-results/test/**/*.xml"
          seconds_between_github_writes: 5
          secondary_rate_limit_wait_seconds: 120

      - name: Run Integration Tests
        if: ${{ steps.unit_test.outcome == 'success' }}
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          ./gradlew --no-daemon --max-workers=2 --warning-mode=all integrationTest --continue --stacktrace

      - name: Publish Integration Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.18
        if: always()
        with:
          check_name: "Integration Test Results"
          files: "**/test-results/integrationTest/**/*.xml"
          seconds_between_github_writes: 5
          secondary_rate_limit_wait_seconds: 120
